# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Art of life
repo_url: github.com/weitzman/art-of-life/
theme:
  name: material
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://mstdn.social/@weitzman
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/weitzman


